language: python
python: "2.7"
cache: pip
install:
  - pip install --upgrade pip wheel  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install flake8
  - pip install -e .[tests]
script: make test
